name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   name: macOS
          #   script: make:macos
            
          # - os: windows-latest
          #   name: Windows
          #   script: make:windows
            
          - os: ubuntu-latest
            name: Linux x64
            script: make:linux

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Install Linux build dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg fakeroot rpm

    - name: Lint code
      run: pnpm run lint

    - name: Test build
      run: pnpm run ${{ matrix.script }}
